### ISSUE TITLE
Item selector issue and other items

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#171] opened 2017-11-06 19:49 UTC
### Step 1:

6 Kindles being used by 6 scouts. Using Bluetooth to transfer spreadsheet to laptop. Using Tableau to display spreadsheet data for analysis.

- Robot Scouter version: 2.0.0-beta3.5639
- Android OS version: 22
- User id: N3qhZLmo1AVm5N5S7qjEWfnzj1R2

### Step 2: Describe the problem: 
Getting ready to field test app at off-season comp this weekend. Trying to create custom template, but "item selector" field is not allowing me to edit. Additionally, when new field is added to template, I need to exit out and re-enter in order to add another field. Also need to know how to delete a field from the custom template. Last but not least, I would like to know how to share the template with the other Kindles being used by our scouts. Thank you!

**Comment by blake1029384756** [comment] 2017-11-07 15:16
Hello @302scouting! The ability to edit the item selector has not been implemented however the dev is able to change it for you manually. Second to delete a field just swipe left on it. After you do so there will be a toast at the bottom incase you want to undo your action. I'm pretty sure you can share templates if you login with the same account on each app. I'm not sure though because I haven't tried.

Hope I could be of some help. Good luck this weekend!

**Comment by SUPERCILEX** [comment] 2017-11-08 08:25
@blake1029384756 Thanks for stepping in! 😄

@302scouting Yep, everything @blake1029384756 said was accurate. For adding an item selector, if you can either tell me the items you need in which item selectors here or in [an email](mailto:saveau.alexandre@gmail.com), I'll add them manually for you. Some other stuff had to be in place before I could get the new item selector going, but it should get done by the end of this week and look something like this:
![img_20171108_002139 1](https://user-images.githubusercontent.com/9490724/32538519-1dfafb1e-c41b-11e7-94ea-fd9c64bbec26.jpg)

You can track my progress here: #165.

As for the template "bug," I'm guessing you mean the big plus button disappears when you add a new metric? If so, this is expected behavior and consistent with other UX in Robot Scouter—the idea is for those big buttons to get out of your way when you don't need them anymore. Simply scroll up and the plus button with animate back in.

Hope this helps, feel free to ask me any more questions! 😄

**Comment by SUPERCILEX** [comment] 2017-11-08 08:36
Relevant to the template editor, some significant improvements were made to keyboard handling and focusing: https://github.com/SUPERCILEX/Robot-Scouter/releases/tag/2.0.0-beta4.

**Comment by 302scouting** [comment] 2017-11-08 19:20
Thank you, Blake. We appreciate your help!

**Comment by SUPERCILEX** [comment] 2017-11-08 20:46
@302scouting Thanks for sharing the template with me, it made it way easier to get its ID. (I'll remember that for future debugging 😄) Anyway, all your item selectors should be set up now.

Also, I got in a crash from you when deleting a stopwatch metric lap. This has been fixed in the latest beta I mentioned above.

Cheers! 😄 I'm closing this issue, but if there's anything else you need, feel free to comment.

**Closed by SUPERCILEX** 2017-11-08 20:46 UTC
Labels: feature:templates, question
