### ISSUE TITLE
[CRASH] Null resources in dialog onShow

### ISSUE THREAD

**Issue by ammarraisafti** [SUPERCILEX/Robot-Scouter#204] opened 2018-05-29 04:50 UTC
# Expected behavior
After enabling Night mode, then select and open the Default template feature, then switch to landscape view mode. The ability to orientate the screen or switch to landscape display mode should be possible.

# Actual behavior
After enabling Night mode, then select and open the Default template feature, then switch to landscape view mode. Suddenly the application crashes and stops.

# How to reproduce
* Launch app. 
* Click the left selection option, then select and open the Settings feature.
* Select and open Night mode feature, then click On.
* Next select and open Default template feature, then switch to landscape display mode. 
* Then you will find the problem as I have explained. *The application crashes and stops.*

<center>Browser: Samsung Galaxy S6 edge
Operating system: Nougat 7.0
App version: 2.3.1.5823</center>

# Recording Of The Bug
https://youtu.be/Qwm30a9w8xg

# Logcat
```
beginning of crash
05-29 11:30:41.025 15166 15166 E AndroidRuntime: FATAL EXCEPTION: main
05-29 11:30:41.025 15166 15166 E AndroidRuntime: Process: com.supercilex.robotscouter, PID: 15166
05-29 11:30:41.025 15166 15166 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.TypedArray android.content.Context.obtainStyledAttributes(int[])' on a null object reference
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at android.support.v7.widget.am.<init>(SourceFile:65)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at com.supercilex.robotscouter.shared.TemplateSelectorDialog$h.<init>(SourceFile:107)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at com.supercilex.robotscouter.shared.TemplateSelectorDialog.a(SourceFile:109)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at com.supercilex.robotscouter.shared.TemplateSelectorDialog$g.onShow(SourceFile:159)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1638)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-29 11:30:41.025 15166 15166 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
05-29 11:30:41.027 15166 15198 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-29 11:30:41.027 15166 15198 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
05-29 11:30:41.028  3166  3706 D EnterpriseController: netId is 0
05-29 11:30:41.028  3166  3706 D Netd    : getNetworkForDns: using netid 501 for uid 10831
05-29 11:30:41.028  3166  3706 D DnsProxyListener: DNSDBG::dns addrinfo af 2
05-29 11:30:41.041  3727  4584 D Debug   : !@DumpState : SHIP
05-29 11:30:41.041  3727  4584 D Debug   : !@DumpState : debug level:0x4f4c
05-29 11:30:41.041  3727  4584 D Debug   : !@Dumpstate : Finally, system will skip dumpstate
05-29 11:30:41.042  3727  4584 W ActivityManager:   Force finishing activity
```

**Comment by SUPERCILEX** [comment] 2018-05-29 05:53
Do you have another device you could reproduce this on by any chance? I can't reproduce it on my side and you're the first to have run into this issue. Also, it should have crashed earlier which doesn't make sense... so I'm kinda leaning towards blaming Samsung.

**Comment by ammarraisafti** [comment] 2018-05-29 06:05
For now only Samsung devices I have, I will try to get another device to try to reproduce this problem. And will tell you, the results I get.

**Comment by SUPERCILEX** [comment] 2018-08-05 03:57
@ammarraisafti Can you try on the latest alpha?

**Comment by SUPERCILEX** [comment] 2018-08-12 07:07
Gonna close this because the codebase has changed quite a bit since the last stable release. If it pops up again, I'll get it in my internal tracker and start investing again.

**Closed by SUPERCILEX** 2018-08-12 07:07 UTC
Labels: bug, feature:scouts, feature:teams, feature:templates
