### ISSUE TITLE
New feature request and question

### ISSUE THREAD

**Issue by 302scouting** [SUPERCILEX/Robot-Scouter#160] opened 2017-09-12 03:44 UTC
### Step 1: Describe your environment

6 to 8 scouts at any given time. Kindles used to collect data. Using Bluetooth to transfer Excel file to laptop. Data analysis done in Tableau on laptop.

* Robot Scouter version: 1.1.2.5344
* Android OS version: 22
* User id: TqIcDU3KvjgZedtvrw6QdADzwTv1
* Scout template keys: []

### Step 2: Describe the problem

Would like to know if there is a way to save scout form layouts to transfer to other Kindles AND to have a backup in case it is accidentally deleted. Would also like to know if there is a way to password protect scout form layout and completed scout forms.

**Comment by SUPERCILEX** [comment] 2017-09-12 04:22
@302scouting Are you planning on using Robot Scouter for an off-season event or would you just like to see this feature for the next season? And do you have data you'd like to transfer over to the next season?

**Comment by SUPERCILEX** [comment] 2017-09-12 04:24
Duplicate of #144 and duplicate of #82.

**Comment by 302scouting** [comment] 2017-09-12 14:44
Thank you for your quick response! We are just doing training test runs in the off-season. These are features we are very interested in having for the next season. We are planning to start with fresh data this season, but are looking to create a season-long database. We will also be doing more formal pit scouting, but that would need to be a separate scout form. I hope that helps clarify.

**Comment by SUPERCILEX** [comment] 2017-09-12 20:22
@302scouting Yep, that clarifies things, thanks! So the reason I asked those questions is because all of the features you mentioned are on the roadmap. The password protecting stuff is for RS `v3.0` which is the 2019 season, but everything else you've mentioned is for RS `v2.0` which is this upcoming 2018 season.

The really cool thing is that all of the scouting form stuff you've mentioned already exists in the [alpha channel (scroll to the bottom)](https://github.com/SUPERCILEX/Robot-Scouter#psst-). There are a few caveats though:
- You'll get tons of updates (sometimes several times a day) after joining the alpha channel. You can leave the Google Plus community at anytime and that will downgrade you to beta. Or you can [leave the beta](https://play.google.com/apps/testing/com.supercilex.robotscouter) to quit completely.
- Do your kindles have the Google Play Store? If they don't, then joining the alpha channel won't work, but I can try to give you an APK.
- You'll lose some of your current data because I'm expecting to wipe the entire database for 2018 anyway. As long as there's nothing important, you should be good.

Other than those points above, if you like the current Robot Scouter, then you're in for a treat in the alpha channel! 😄 

PS: as for syncing with other devices, you just have to sign in with the same account on each device and a bunch of magic will happen automatically.

Please let me know if you need any clarification.

**Comment by 302scouting** [comment] 2017-09-20 10:06
Good morning. We did some off-season comp testing of the scouting app this past weekend and it went well. Among other things, I was very pleased with the low battery draw of your app. Kudos to you! (We did the testing with the beta version to keep it simple, but will be trying out the alpha now.) That said, we did run across one snafu. We were transferring the collected data via excel file from the Kindles to a laptop and had to individually copy/paste data one sheet at a time from each Kindle's transferred Excel file to our Master Excel file. Do you have a quicker/easier/more direct suggestion for doing this? Thank you in advance for your help.

**Comment by SUPERCILEX** [comment] 2017-09-20 14:40
@302scouting glad to hear it went well! Yes, you should be able to transfer one big export file from a single Kindle that has all the data. If you see an arrow pointing inside a square at the top right of RS, it means you aren't signed in. If you sign in, all your data will be synced across devices automatically.

Something to note: you _do_ have to connect to the internet for the syncing with to happen, but I'm try to fix that for the next season.

PS: I've given you access to the alpha channel, but I'm in the middle of rewriting the database so things might be a little funky and/or crash.

**Comment by SUPERCILEX** [comment] 2017-09-25 00:58
@302scouting I just released an update to the alpha yesterday that brings (nearly) complete feature parity between the 1.0 and 2.0 databases, so I'm going to close this issue.

If you're having an trouble either with syncing data between devices or anything else, please let me know.

**Closed by SUPERCILEX** 2017-09-25 00:58 UTC
Labels: feature, feature:templates, fix-implemented
