### ISSUE TITLE
Robot Scouter v 2.3.1.5823 Fatal exception in android 7.0 when doing screen orientation

### ISSUE THREAD

**Issue by ammarraisafti** [SUPERCILEX/Robot-Scouter#205] opened 2018-05-30 13:01 UTC
#### Expected behavior
After select and open the Donate feature, the ability to switch to landscape view mode should be possible. And I believe the screen orientation capability of this on feature can be applied.

#### Actual behavior
After select and open Donate feature, then I switch to landscape display mode. Unfortunately, the screen orientation capability can not be done, because the Application suddenly crashes and stops.

###### Here are the steps to do to generate a bug.
> Browser: Samsung Galaxy S6 edge
> Operating system: Nougat 7.0
> App version: 2.3.1.5823 

* Launch app
* Select the Night mode feature, and choose the ON option.
* Close the application and re-open to activate the night mode
* Click the left selection option
* Select and open **Donate** features
* Perform screen orientation, or switch to landscape display mode
* Problems coming soon. _**The application suddenly crashes and stops.**_

#### Recording Of The Bug
Here is a screen video recording that shows how to produce Bug, as well as problems that occur.

https://youtu.be/peZF3fdUmZo

#### Logcat
Here are some lines of error fatal exception code that I found in logcat.

```<code> --------- beginning of crash
05-30 18:28:33.431 19676 19676 E AndroidRuntime: FATAL EXCEPTION: main
05-30 18:28:33.431 19676 19676 E AndroidRuntime: Process: com.supercilex.robotscouter, PID: 19676
05-30 18:28:33.431 19676 19676 E AndroidRuntime: java.lang.IllegalStateException: Fragment DonateDialog{3f81c61} not attached to a context.
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at android.support.v4.app.j.p(SourceFile:614)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at android.support.v4.app.j.a(SourceFile:9678)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onProgressChanged(SourceFile:57)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onShow(SourceFile:53)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at com.supercilex.robotscouter.core.ui.c$b.onShow(SourceFile:83)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1638)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-30 18:28:33.431 19676 19676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: FATAL EXCEPTION: main
05-30 18:28:43.666 20314 20314 E AndroidRuntime: Process: com.supercilex.robotscouter, PID: 20314
05-30 18:28:43.666 20314 20314 E AndroidRuntime: java.lang.IllegalStateException: Fragment DonateDialog{46c3a81} not attached to a context.
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at android.support.v4.app.j.p(SourceFile:614)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at android.support.v4.app.j.a(SourceFile:9678)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onProgressChanged(SourceFile:57)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onShow(SourceFile:53)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at com.supercilex.robotscouter.core.ui.c$b.onShow(SourceFile:83)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1638)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-30 18:28:43.666 20314 20314 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: FATAL EXCEPTION: main
05-30 18:28:55.166 20446 20446 E AndroidRuntime: Process: com.supercilex.robotscouter, PID: 20446
05-30 18:28:55.166 20446 20446 E AndroidRuntime: java.lang.IllegalStateException: Fragment DonateDialog{ab6ed10} not attached to a context.
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at android.support.v4.app.j.p(SourceFile:614)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at android.support.v4.app.j.a(SourceFile:9678)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onProgressChanged(SourceFile:57)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onShow(SourceFile:53)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at com.supercilex.robotscouter.core.ui.c$b.onShow(SourceFile:83)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1638)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-30 18:28:55.166 20446 20446 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: FATAL EXCEPTION: main
05-30 18:29:22.416 20583 20583 E AndroidRuntime: Process: com.supercilex.robotscouter, PID: 20583
05-30 18:29:22.416 20583 20583 E AndroidRuntime: java.lang.IllegalStateException: Fragment DonateDialog{28adce4} not attached to a context.
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at android.support.v4.app.j.p(SourceFile:614)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at android.support.v4.app.j.a(SourceFile:9678)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onProgressChanged(SourceFile:57)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at com.supercilex.robotscouter.DonateDialog.onShow(SourceFile:53)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at com.supercilex.robotscouter.core.ui.c$b.onShow(SourceFile:83)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1638)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
05-30 18:29:22.416 20583 20583 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)</code>```

**Comment by SUPERCILEX** [comment] 2018-06-01 04:47
Duplicate of #204. This is the same frustratingly nonsensical null context bug.

**Closed by SUPERCILEX** 2018-06-01 04:47 UTC
Labels: bug
